version: "4"
services:
  web: 
    hostname: web
    restart: always
    build:
      context: .
      dockerfile: dockerfile_web
    ports:
      - "80:80"

  rails: 
    hostname: rails
    restart: always
    build:
      context: .
      dockerfile: dockerfile_rails
    ports:
      - "3000:3000"

